### ISSUE TITLE
Add Porter to the list

### ISSUE THREAD

**Issue by adieu** [vnbrs/digest#1]
Hello, we build a service called [Porter](https://porter.io) which collects hacker news submissions, filters out open source related news and sends out daily digest to developers. It might be quite relevant to the daily digest topic.

We also have a [explore page](https://porter.io/explore/) which lists all new repos submitted to hacker news. That's where I found this repo :)

**Comment by vinibrsl** [comment]
Hello! I didn't know Porter. Already started using it, and it's great!

I have added it to the list. :shipit:
